logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#rabbitmq的相关配置
spring:
  rabbitmq:
    host: 192.168.179.128
    port: 5672
    username: itecast
    password: 123321
    virtual-host: /
    listener:
      simple:
        prefetch: 1